[language-server.pyright-docker]
command = "docker"
args = [
  "exec", "-i",
  "--workdir", "/home/user/Workspace/cleany/ros2_ws",
  "cleany-humble-dev",
  "bash", "-lc",
  "source /opt/ros/humble/setup.bash && if [[ -f /workspace/cleany/ros2_ws/install/setup.bash ]]; then source /workspace/cleany/ros2_ws/install/setup.bash; fi && exec pyright-langserver --stdio",
]

[[language]]
name = "python"
language-servers = ["pyright-docker"]
roots = ["pyrightconfig.json", "package.xml", "setup.py", "setup.cfg", ".git"]
