[language-server.pyright-docker]
command = "../scripts/pyright-docker"

[[language]]
name = "python"
language-servers = ["pyright-docker"]
roots = ["pyrightconfig.json", "package.xml", "setup.py", "setup.cfg", ".git"]
